version: "3"
services:
  frontend:
    build:
        context: .
        dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules # using volume overrides the image's file
    depends_on:
      - server

  server:
    build:
        context: .
        dockerfile: Dockerfile.server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app/server # only check for changes in server otherwise the volume is too large
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1